version: '3.8'

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - prisma-postgres:/var/lib/postgresql/data
    ports:
      - '5440:5432'
    networks:
      - prisma-nexus-network

networks:
  prisma-nexus-network:
    driver: bridge

volumes:
  prisma-postgres:
